### ISSUE TITLE
downloading the DynaKITTI dataset

### ISSUE THREAD

**Issue by liuzefengi** [castacks/DytanVO#10]
Thank you for your outstanding work, I have a problem that I would like to ask: I am downloading the DynaKITTI dataset and it always says that I can't get it from the website or I don't have permission to download it, I would like to get your help. Thank you very much.

**Comment by Geniussh** [comment]
I just tried to download it and I was able to do so. As it's on the google drive, have you tried to download it using VPN? Another way to download it, which I have just tested personally too, is to use gdown in the command line.
```
pip install gdown
gdown 1BDnraRWzNf938UsfprWIkcqCSfOUyGt9
```
Let me know if it still doesn't work.

**Comment by liuzefengi** [comment]
Thanks for the reply, I used a VPN for the download but still had problems halfway through the download!
![选区_046](https://github.com/castacks/DytanVO/assets/131932700/73ab13bd-0b51-468f-afa3-83252b35deeb)
![选区_045](https://github.com/castacks/DytanVO/assets/131932700/c7872e40-a867-4606-a768-e03572c3536d)

**Comment by Geniussh** [comment]
Doesn't the last screenshot already show it was successfully downloaded to your $HOME?

**Comment by liuzefengi** [comment]
Thank you for your patience, the problem has been solved, I didn't have the file in my directory when it first showed success, I re-downloaded it a few times and it finally worked, thanks again!
