### ISSUE TITLE
Questions about table 2 in the paper

### ISSUE THREAD

**Issue by a541203686** [castacks/DytanVO#12]
Hello, I'd like to inquire about Table 2 in the paper. Could you please provide an explanation for the results of dynamic KITII sequences 00, 01, and 02? I've successfully generated the results for sequence 00 using the file labeled 00_1. However, for the dynamic KITII sequence 02, I've noticed three folders named 02_0, 02_1, and 02_2. Could you kindly guide me on how to obtain the results to populate Table 2?

**Comment by Geniussh** [comment]
02_0, 02_1 and 02_2 are just three sub-trajectories of 02 that contain dynamic objects. As far as I can remember, we used 02_1 as the result to show in Table 2. The same applies to the other sub-trajectories.

**Comment by a541203686** [comment]
Thanks for your reply!
