### ISSUE TITLE
this code need rgbd camera ？ may i  test with mono usb camera？

### ISSUE THREAD

**Issue by cudnn** [castacks/DytanVO#7]
this code need rgbd camera ？ may i  test with mono usb camera？

**Comment by Geniussh** [comment]
DytanVO is a monocular VO method, so yes you should always have rgb or monochrome images as input. 

We do have variants that take in either image pair from a stereo setup or depth directly. We will consider making those open source in the near future.

**Comment by cudnn** [comment]
nice，i need monocular VO；
